### ISSUE TITLE
Error on get_summary

### ISSUE THREAD

**Issue by OrChen17** [Intsights/sergeant#31]
in certain cases, worker.get_summary() returns None
when that happens and the return code is 1, an exception is  thrown. =>
```

 
--
Traceback (most recent call last):   File "/usr/local/lib/python3.9/site-packages/sergeant/supervisor.py", line 157, in supervise_loop     self.supervise_worker(   File "/usr/local/lib/python3.9/site-packages/sergeant/supervisor.py", line 234, in supervise_worker     msg=f'worker({worker.process.pid}) execution has failed with the following exception: {extra_signature["summary"].get("exception")}', AttributeError: 'NoneType' object has no attribute 'get'
  |  

```
it should return an empty dict instead

**Comment by wavenator** [comment]
What version are you using?
